language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
notifications:
  slack: lovebankworkspace:jxHHnVQhjeNqMvZosCgFr19T

# deploy on Heroku if test passed
deploy:
  provider: heroku
  api_key: $HEROKU_API_SECRET
  app: lovebank
  on:
    all_branches: true
