"""empty message

Revision ID: 2aba7fc1308d
Revises: ebdf22a2cf8f
Create Date: 2020-06-08 21:03:41.904147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aba7fc1308d'
down_revision = 'ebdf22a2cf8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('accepted', sa.Boolean(), nullable=True))
    op.add_column('task', sa.Column('compTime', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('cost', sa.Integer(), nullable=False))
    op.add_column('task', sa.Column('creationTime', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.add_column('task', sa.Column('deadline', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('description', sa.String(length=120), nullable=False))
    op.add_column('task', sa.Column('done', sa.Boolean(), nullable=True))
    op.add_column('task', sa.Column('receiver_id', sa.Integer(), nullable=False))
    op.add_column('task', sa.Column('title', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('balance', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('partner_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user', ['partner_id'])
    op.create_foreign_key(None, 'task', 'user', ['creator_id'], ['id'])
    op.create_foreign_key(None, 'task', 'user', ['receiver_id'], ['partner_id'])
    op.drop_column('task', 'task_title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'partner_id')
    op.drop_column('user', 'balance')
    op.add_column('task', sa.Column('task_title', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_column('task', 'title')
    op.drop_column('task', 'receiver_id')
    op.drop_column('task', 'done')
    op.drop_column('task', 'description')
    op.drop_column('task', 'deadline')
    op.drop_column('task', 'creator_id')
    op.drop_column('task', 'creationTime')
    op.drop_column('task', 'cost')
    op.drop_column('task', 'compTime')
    op.drop_column('task', 'accepted')
    # ### end Alembic commands ###
