"""empty message

Revision ID: 6e262665bf90
Revises: 45db712dfbe0
Create Date: 2020-06-24 17:50:10.056236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e262665bf90'
down_revision = '45db712dfbe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('invite_code', sa.String(length=8), nullable=True))
    op.add_column('user', sa.Column('phone', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'user', ['id'])
    op.create_unique_constraint(None, 'user', ['phone'])
    op.create_unique_constraint(None, 'user', ['invite_code'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'invite_code')
    # ### end Alembic commands ###
