"""empty message

Revision ID: eb7932ee0945
Revises: 0b1d12aa49b0
Create Date: 2020-06-10 23:11:21.747071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb7932ee0945'
down_revision = '0b1d12aa49b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_receiver_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'user', ['receiver_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_receiver_id_fkey', 'task', 'user', ['receiver_id'], ['partner_id'])
    # ### end Alembic commands ###
