"""empty message

Revision ID: ebdf22a2cf8f
Revises: db511338a08f
Create Date: 2020-06-08 12:12:55.472606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebdf22a2cf8f'
down_revision = 'db511338a08f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task_title', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'task_title')
    # ### end Alembic commands ###
